# Generated by Django 3.0.7 on 2020-06-23 21:42

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Beneficiario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dap', models.CharField(max_length=25)),
                ('enquadramento', models.CharField(max_length=25)),
                ('categoria', models.CharField(max_length=50)),
                ('nome', models.CharField(max_length=150)),
                ('UF', models.CharField(max_length=2)),
                ('municipio', models.CharField(max_length=50)),
                ('data_emissao', models.DateField()),
                ('data_validade', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='BeneficiarioFinal',
            fields=[
                ('cpf', models.CharField(max_length=11, null=True)),
                ('nome', models.CharField(max_length=150)),
                ('nis', models.CharField(max_length=11, primary_key=True, serialize=False)),
                ('data_nascimento', models.DateField()),
                ('cod_ibge_munic_nasc', models.CharField(max_length=7)),
                ('identidade', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Cooperativa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Entidade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Ponto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('entidade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='relatorios.Entidade')),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=100, unique=True)),
                ('senha', models.CharField(max_length=100)),
                ('admin', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='TransacaoFinal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('litros', models.FloatField()),
                ('tipo', models.CharField(choices=[('1', 'VACA'), ('2', 'CABRA')], default='1', max_length=10)),
                ('data', models.DateField(default=django.utils.timezone.now)),
                ('beneficiario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='relatorios.BeneficiarioFinal')),
                ('ponto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='relatorios.Ponto')),
            ],
        ),
        migrations.CreateModel(
            name='Transacao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('litros', models.FloatField()),
                ('tipo', models.CharField(choices=[('1', 'VACA'), ('2', 'CABRA')], default='1', max_length=10)),
                ('data', models.DateField(default=django.utils.timezone.now)),
                ('beneficiario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='relatorios.Beneficiario')),
                ('cooperativa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='relatorios.Cooperativa')),
            ],
        ),
        migrations.AddField(
            model_name='ponto',
            name='membro',
            field=models.ManyToManyField(to='relatorios.Usuario'),
        ),
        migrations.AddField(
            model_name='cooperativa',
            name='membro',
            field=models.ManyToManyField(to='relatorios.Usuario'),
        ),
    ]
