# Generated by Django 3.0.7 on 2020-06-10 20:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cooperativa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=100)),
                ('senha', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Transacao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('litros', models.FloatField()),
                ('tipo', models.CharField(choices=[('1', 'VACA'), ('2', 'CABRA')], default='1', max_length=10)),
                ('cooperativa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='relatorios.Cooperativa')),
            ],
        ),
        migrations.AddField(
            model_name='cooperativa',
            name='membro',
            field=models.ManyToManyField(to='relatorios.Usuario'),
        ),
    ]
