# Generated by Django 3.0.7 on 2020-07-09 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relatorios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='coop_bool',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='usuario',
            name='ponto_bool',
            field=models.BooleanField(default=False),
        ),
    ]
