# Generated by Django 3.0.7 on 2020-06-10 20:42

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('relatorios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transacao',
            name='data',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='usuario',
            name='admin',
            field=models.BooleanField(default=False),
        ),
    ]
