# Generated by Django 3.0.7 on 2020-06-23 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relatorios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beneficiariofinal',
            name='identidade',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
