# Generated by Django 3.0.7 on 2020-07-09 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relatorios', '0002_auto_20200709_1513'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='seagri_bool',
            field=models.BooleanField(default=False),
        ),
    ]
