# Generated by Django 3.0.7 on 2020-06-23 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relatorios', '0002_auto_20200623_1848'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beneficiariofinal',
            name='cod_ibge_munic_nasc',
            field=models.CharField(max_length=7, null=True),
        ),
        migrations.AlterField(
            model_name='beneficiariofinal',
            name='data_nascimento',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='beneficiariofinal',
            name='nome',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
