# Generated by Django 3.0.7 on 2020-06-15 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relatorios', '0003_auto_20200612_1417'),
    ]

    operations = [
        migrations.CreateModel(
            name='Beneficiario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dap', models.CharField(max_length=25)),
                ('enquadramento', models.CharField(max_length=25)),
                ('categoria', models.CharField(max_length=50)),
                ('nome', models.CharField(max_length=50)),
                ('UF', models.CharField(max_length=2)),
                ('MUNICIPIO', models.CharField(max_length=50)),
                ('DATA_EMISSAO', models.DateField()),
                ('DATA_VALIDADE', models.DateField()),
            ],
        ),
    ]
