# Generated by Django 3.0.7 on 2020-08-10 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relatorios', '0003_usuario_seagri_bool'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ponto',
            name='entidade',
            field=models.BooleanField(default=False),
        ),
    ]
