# Generated by Django 3.0.7 on 2020-08-10 17:37

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('relatorios', '0004_auto_20200810_0944'),
    ]

    operations = [
        migrations.AddField(
            model_name='ponto',
            name='limit_ben',
            field=models.IntegerField(default=50),
        ),
        migrations.AddField(
            model_name='transacao',
            name='usuario',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='relatorios.Usuario'),
        ),
        migrations.AddField(
            model_name='transacaofinal',
            name='usuario',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='relatorios.Usuario'),
        ),
        migrations.CreateModel(
            name='RelatoPonto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=144)),
                ('data', models.DateField(default=django.utils.timezone.now)),
                ('ponto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='relatorios.Ponto')),
                ('usuario', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='relatorios.Usuario')),
            ],
        ),
    ]
