# Generated by Django 3.0.7 on 2020-08-14 20:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('relatorios', '0004_usuario_telefone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ponto',
            name='entidade',
        ),
        migrations.DeleteModel(
            name='Entidade',
        ),
    ]
