# Generated by Django 3.0.7 on 2020-06-15 17:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('relatorios', '0004_beneficiario'),
    ]

    operations = [
        migrations.RenameField(
            model_name='beneficiario',
            old_name='DATA_EMISSAO',
            new_name='data_emissao',
        ),
        migrations.RenameField(
            model_name='beneficiario',
            old_name='DATA_VALIDADE',
            new_name='data_valdiade',
        ),
        migrations.RenameField(
            model_name='beneficiario',
            old_name='MUNICIPIO',
            new_name='municipio',
        ),
    ]
