# Generated by Django 3.0.7 on 2020-08-14 21:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('relatorios', '0005_auto_20200814_1741'),
    ]

    operations = [
        migrations.CreateModel(
            name='Localizacao',
            fields=[
                ('cod_ibge', models.CharField(max_length=7, primary_key=True, serialize=False)),
                ('uf', models.CharField(max_length=2)),
                ('municipio', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='cooperativa',
            name='cnpj',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='cooperativa',
            name='endereco',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='cooperativa',
            name='responsavel',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='cooperativa',
            name='sigla',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='ponto',
            name='cnpj',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='ponto',
            name='coop',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='relatorios.Cooperativa'),
        ),
        migrations.AddField(
            model_name='ponto',
            name='endereco',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='cooperativa',
            name='cod_ibge',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='relatorios.Localizacao'),
        ),
        migrations.AddField(
            model_name='ponto',
            name='cod_ibge',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='relatorios.Localizacao'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='cod_ibge',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='relatorios.Localizacao'),
        ),
    ]
