# Generated by Django 3.0.7 on 2020-06-15 20:35

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('relatorios', '0006_delete_transacao'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transacao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('litros', models.FloatField()),
                ('tipo', models.CharField(choices=[('1', 'VACA'), ('2', 'CABRA')], default='1', max_length=10)),
                ('data', models.DateField(default=django.utils.timezone.now)),
                ('beneficiario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='relatorios.Beneficiario')),
                ('cooperativa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='relatorios.Cooperativa')),
            ],
        ),
    ]
