# Generated by Django 3.0.7 on 2020-06-15 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relatorios', '0007_transacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beneficiario',
            name='nome',
            field=models.CharField(max_length=150),
        ),
    ]
