# Generated by Django 3.0.7 on 2020-08-14 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relatorios', '0007_remove_cooperativa_cod_ibge'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cooperativa',
            name='nome',
            field=models.CharField(max_length=150),
        ),
    ]
