# Generated by Django 3.0.7 on 2020-08-14 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relatorios', '0008_auto_20200814_1819'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ponto',
            name='endereco',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='ponto',
            name='nome',
            field=models.CharField(max_length=150),
        ),
    ]
