# Generated by Django 3.0.7 on 2020-06-15 22:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('relatorios', '0008_auto_20200615_1852'),
    ]

    operations = [
        migrations.RenameField(
            model_name='beneficiario',
            old_name='data_valdiade',
            new_name='data_validade',
        ),
    ]
