# Generated by Django 3.0.7 on 2020-08-14 21:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('relatorios', '0009_auto_20200814_1828'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ponto',
            name='coop',
        ),
    ]
