# Generated by Django 3.0.7 on 2020-08-14 21:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('relatorios', '0010_remove_ponto_coop'),
    ]

    operations = [
        migrations.AddField(
            model_name='ponto',
            name='coop',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='relatorios.Cooperativa'),
        ),
    ]
