# Generated by Django 3.0.7 on 2020-08-18 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relatorios', '0011_ponto_coop'),
    ]

    operations = [
        migrations.AddField(
            model_name='beneficiariofinal',
            name='data_att',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='beneficiariofinal',
            name='faixa_renda',
            field=models.IntegerField(default=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='beneficiariofinal',
            name='nome_mae',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='ponto',
            name='cnpj',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='ponto',
            name='endereco',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='ponto',
            name='membro',
            field=models.ManyToManyField(blank=True, to='relatorios.Usuario'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='telefone',
            field=models.CharField(blank=True, default=None, max_length=50, null=True),
        ),
    ]
