# Generated by Django 3.0.7 on 2020-08-31 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relatorios', '0012_auto_20200818_1116'),
    ]

    operations = [
        migrations.AddField(
            model_name='ponto',
            name='limit_beneficiarios',
            field=models.IntegerField(default=0),
        ),
    ]
