# Generated by Django 3.0.7 on 2020-09-21 18:32

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('relatorios', '0013_ponto_limit_beneficiarios'),
    ]

    operations = [
        migrations.CreateModel(
            name='Entidade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
                ('cnpj', models.CharField(max_length=50)),
                ('rep_nome', models.CharField(max_length=150)),
                ('rep_end', models.CharField(blank=True, max_length=150)),
                ('email', models.CharField(max_length=150)),
                ('tipo', models.IntegerField(default=1)),
                ('limit_beneficiarios', models.IntegerField(default=0)),
                ('cod_ibge', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='relatorios.Localizacao')),
                ('coop', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='relatorios.Cooperativa')),
            ],
        ),
        migrations.AddField(
            model_name='usuario',
            name='entidade_bool',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='TransacaoEntidade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('litros', models.FloatField()),
                ('data', models.DateField(default=django.utils.timezone.now)),
                ('ben_0_6', models.IntegerField(default=0)),
                ('ben_7_14', models.IntegerField(default=0)),
                ('ben_15_23', models.IntegerField(default=0)),
                ('ben_24_65', models.IntegerField(default=0)),
                ('ben_66_mais', models.IntegerField(default=0)),
                ('ben_m', models.IntegerField(default=0)),
                ('ben_f', models.IntegerField(default=0)),
                ('entidade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='relatorios.Entidade')),
            ],
        ),
        migrations.AddField(
            model_name='entidade',
            name='membro',
            field=models.ManyToManyField(blank=True, to='relatorios.Usuario'),
        ),
    ]
