# Generated by Django 3.0.7 on 2020-09-22 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relatorios', '0014_auto_20200921_1532'),
    ]

    operations = [
        migrations.RenameField(
            model_name='entidade',
            old_name='email',
            new_name='rep_email',
        ),
        migrations.AddField(
            model_name='entidade',
            name='rep_cpf',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='entidade',
            name='rep_tel',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
