# Generated by Django 3.0.7 on 2020-09-23 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('relatorios', '0015_auto_20200922_1539'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entidade',
            name='limit_beneficiarios',
        ),
    ]
