# Generated by Django 3.0.7 on 2020-09-23 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relatorios', '0016_remove_entidade_limit_beneficiarios'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='beneficiario',
            name='id',
        ),
        migrations.AlterField(
            model_name='beneficiario',
            name='dap',
            field=models.CharField(max_length=50),
        ),
    ]
