# Generated by Django 3.0.7 on 2020-09-23 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relatorios', '0017_auto_20200923_0947'),
    ]

    operations = [
        migrations.AddField(
            model_name='beneficiario',
            name='validade',
            field=models.CharField(default='', max_length=25),
            preserve_default=False,
        ),
    ]
