# Generated by Django 3.0.7 on 2020-09-23 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('relatorios', '0018_beneficiario_validade'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='beneficiario',
            name='validade',
        ),
    ]
