# Generated by Django 3.0.7 on 2020-09-28 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relatorios', '0019_remove_beneficiario_validade'),
    ]

    operations = [
        migrations.AddField(
            model_name='beneficiario',
            name='cpf',
            field=models.CharField(max_length=14, null=True),
        ),
        migrations.AlterField(
            model_name='beneficiario',
            name='dap',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
    ]
