# Generated by Django 3.0.7 on 2020-09-28 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relatorios', '0020_auto_20200928_1204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transacao',
            name='beneficiario',
            field=models.CharField(max_length=10),
        ),
    ]
