# Generated by Django 3.0.7 on 2020-09-28 16:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('relatorios', '0021_auto_20200928_1317'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transacao',
            name='beneficiario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='relatorios.Beneficiario'),
        ),
    ]
