# Generated by Django 3.0.7 on 2020-10-01 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relatorios', '0022_auto_20200928_1318'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entidade',
            name='cnpj',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='entidade',
            name='rep_cpf',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
