# Generated by Django 3.0.7 on 2020-10-06 17:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('relatorios', '0023_auto_20201001_1516'),
    ]

    operations = [
        migrations.AddField(
            model_name='beneficiario',
            name='sexo',
            field=models.CharField(default='', max_length=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cooperativa',
            name='cod_ibge',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='relatorios.Localizacao'),
        ),
        migrations.AddField(
            model_name='cooperativa',
            name='dap',
            field=models.CharField(default='', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='localizacao',
            name='territorio',
            field=models.CharField(default='', max_length=50, null=True),
        ),
        migrations.CreateModel(
            name='Laticinio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
                ('cnpj', models.CharField(blank=True, max_length=50, null=True)),
                ('cod_ibge', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='relatorios.Localizacao')),
                ('coop', models.ManyToManyField(blank=True, to='relatorios.Cooperativa')),
            ],
        ),
    ]
