# Generated by Django 3.0.7 on 2020-10-06 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relatorios', '0024_auto_20201006_1413'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beneficiario',
            name='sexo',
            field=models.CharField(default='', max_length=1, null=True),
        ),
    ]
