# Generated by Django 3.0.7 on 2020-10-19 19:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('relatorios', '0025_auto_20201006_1413'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transacao',
            options={'verbose_name': 'Transação Produtor', 'verbose_name_plural': 'Transações de Produtores'},
        ),
        migrations.AlterModelOptions(
            name='transacaoentidade',
            options={'verbose_name': 'Transação Entidade', 'verbose_name_plural': 'Transações de Entidades'},
        ),
        migrations.AlterModelOptions(
            name='transacaofinal',
            options={'verbose_name': 'Transação Consumidor', 'verbose_name_plural': 'Transações para Consumidores'},
        ),
        migrations.AddField(
            model_name='transacao',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='relatorios.Usuario'),
        ),
    ]
