# Generated by Django 3.0.7 on 2020-10-19 19:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('relatorios', '0026_auto_20201019_1600'),
    ]

    operations = [
        migrations.AddField(
            model_name='transacaoentidade',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='relatorios.Usuario'),
        ),
        migrations.AddField(
            model_name='transacaofinal',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='relatorios.Usuario'),
        ),
    ]
