# Generated by Django 3.0.7 on 2020-12-14 17:22

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('relatorios', '0027_auto_20201019_1602'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='beneficiario',
            options={'verbose_name': 'Produtor', 'verbose_name_plural': 'Produtores'},
        ),
        migrations.AlterModelOptions(
            name='beneficiariofinal',
            options={'verbose_name': 'Consumidor', 'verbose_name_plural': 'Consumidores'},
        ),
        migrations.CreateModel(
            name='OcorrenciaPonto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(default=django.utils.timezone.now)),
                ('descricao', models.CharField(max_length=150)),
                ('ponto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='relatorios.Ponto')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='relatorios.Usuario')),
            ],
            options={
                'verbose_name': 'Ocorrência de Ponto',
                'verbose_name_plural': 'Ocorrências de Ponto',
            },
        ),
        migrations.CreateModel(
            name='OcorrenciaCoop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(default=django.utils.timezone.now)),
                ('descricao', models.CharField(max_length=150)),
                ('coop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='relatorios.Cooperativa')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='relatorios.Usuario')),
            ],
            options={
                'verbose_name': 'Ocorrência de Cooperativa',
                'verbose_name_plural': 'Ocorrências de Cooperativa',
            },
        ),
    ]
