# Generated by Django 3.0.7 on 2020-12-15 12:53

from django.db import migrations, models
import relatorios.models


class Migration(migrations.Migration):

    dependencies = [
        ('relatorios', '0028_auto_20201214_1422'),
    ]

    operations = [
        
        
    ]
