# Generated by Django 3.0.7 on 2020-12-15 13:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('relatorios', '0029_auto_20201215_0953'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OcorrenciaCoop',
        ),
    ]
