# Generated by Django 3.0.7 on 2021-01-04 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relatorios', '0031_ocorrenciaponto_foto'),
    ]

    operations = [
        migrations.AddField(
            model_name='ocorrenciaponto',
            name='viewed',
            field=models.BooleanField(default=False),
        ),
    ]
