# Generated by Django 3.0.7 on 2021-02-09 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relatorios', '0032_ocorrenciaponto_viewed'),
    ]

    operations = [
        migrations.AddField(
            model_name='beneficiario',
            name='pbf',
            field=models.BooleanField(default=False),
        ),
    ]
