# Generated by Django 3.0.7 on 2021-02-09 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relatorios', '0033_beneficiario_pbf'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='beneficiario',
            name='pbf',
        ),
        migrations.AddField(
            model_name='beneficiariofinal',
            name='pbf',
            field=models.BooleanField(default=False),
        ),
    ]
