# Generated by Django 3.0.7 on 2021-02-09 20:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relatorios', '0034_auto_20210209_1321'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beneficiariofinal',
            name='data_att',
            field=models.DateField(blank=True, default=datetime.datetime.now, null=True),
        ),
    ]
