# Generated by Django 4.1.5 on 2023-02-28 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relatorios', '0035_auto_20210209_1715'),
    ]

    operations = [
        migrations.AddField(
            model_name='beneficiario',
            name='ativo',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='beneficiariofinal',
            name='ativo',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='beneficiariofinal',
            name='telefone',
            field=models.CharField(blank=True, max_length=11, null=True),
        ),
    ]
